version: '3'

services:
  superDB:
    image: postgres:15.3
    container_name: super-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresv
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

