import type { Metadata } from "next";
import { inter } from "@/config/fonts";
import "./globals.css";
import { UserProvider } from "@/providers/UserProvider";

export const metadata: Metadata = {
  title: "Supervision App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
